branches:
  only:
    master
language: node_js
env:
  global:
    - SQRL_TEST_REDIS=localhost:6379
matrix:
  include:
    - node_js: "11.10.1"
    - node_js: "8"
      if: type = push AND branch = master
    - node_js: "10"
      if: type = push AND branch = master
services:
  - redis-server
install:
  - npm ci
script:
  - npm run build
  - npm run test:integration -- --coverage
  - "redis-cli get 'sqrl:test' | grep '^okay'"
after_script:
  - "cat coverage/lcov.info | ./node_modules/.bin/coveralls" # sends the coverage report to coveralls
